### ISSUE TITLE
add documentation

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-tag#16]
Deploy on the gh-pages branch.

Visible on https://imise.github.io/snik-tag/

Investigate Git Playbook: https://github.com/thomasreinecke/git-playbook https://itnext.io/create-compelling-documentation-with-github-pages-16e4149efe9e

**Comment by ThomasPause** [comment]
documentation is nearly finished, on doc branch, links are set in the tool and on top of the repo.
For now, git playbook does not run well, so maybe switch to jekyll, therefore leave this issue open
