### ISSUE TITLE
grenzt sich snik tag von GATE ab?

### ISSUE THREAD

**Issue by ThomasPause** [IMISE/snik-tag#19]
...und in wie fern??

**Comment by KonradHoeffner** [comment]
There are multiple [GATE products](https://gate.ac.uk/family/) but the most fitting seems to be [GATE Teamware](https://gate.ac.uk/teamware/), 

> a collaborative annotation environment for high volume factory-style semantic annotation projects built around a workflow engine and the GATE cloud backend web services

Most cited paper ([Download](https://link.springer.com/content/pdf/10.1007/s10579-013-9215-6.pdf)):

```
@article{bontcheva2013gate,
  title={GATE Teamware: a web-based, collaborative text annotation framework},
  author={Bontcheva, Kalina and Cunningham, Hamish and Roberts, Ian and Roberts, Angus and Tablan, Valentin and Aswani, Niraj and Gorrell, Genevieve},
  journal={Language Resources and Evaluation},
  volume={47},
  number={4},
  pages={1007--1029},
  year={2013},
  publisher={Springer}
}
```

Most relevant parts of the [Introduction](https://gate.ac.uk/teamware/teamware-detail.html):

> Semantic Annotation (SA) is about attaching meaningful structures to resources like documents or video streams in such a way that they can be used by computers to enhance the usefulness of those resources.

>SA is not new: when a BBC archivist, for example, attaches thesaurus categories to programme segments for indexing they have > performed semantic annotation. SA technology has changed, however, in two main ways:
>   * the invention of Information Extraction in the 1990s has made automatic SA more possible
>   * recent research around the Semantic Web has shown how SA can be used for scaleable conceptual search and navigation products in specific domains
> The requisite **annotation can be done manually**, and this **works well** in cases like flikr and delicio.us where the **annotators benefit directly from their own work** (creating their own "folksonomies").
> In other cases, where the task is simple and the domain of application specific, automatic annotation can work to an acceptable accuracy level [...]
> **Where neither of these things is true** what is needed is an **Annotation Factory** [...]
> **GATE Teamware** is a software suite and methodology **for implementing annotation factories**

In our case, the annotation can be done manually and is not simple, so GATE is not the right tool for our purpose.
