### ISSUE TITLE
add definition column

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-tag#52]
Free-text column to add a definition.
First one to work on this issue removes the other assignee so we don't mistakenly both do it.

**Comment by Yagnap** [comment]
Working on this now.

**Comment by Yagnap** [comment]
Still need to do the export and maybe make it prettier by using an Enum instead of Strings

**Comment by Yagnap** [comment]
resolved in e404978e12885a4239e311ecd0eb421766310aa9, doesn't seem to be easily made prettier without much work and redesign
